#app.yaml

runtime: python27
api_version: 1
threadsafe: True

handlers:
  - url: /style
    static_dir: style 
    script: main.app

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest
